#version: '3.8'
services:
  e-commerce-dp:
    image: postgres:latest
    ports:
      - "5432:5432"

    restart : always
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_database

  e-commerce-zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    restart : always

  e-commerce-kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: e-commerce-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - e-commerce-zookeeper

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka

  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka
  checkout-service:
    build:
      context: ./checkout-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka
  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka
  security-service:
    build:
      context: ./security-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka
  shipping-service:
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka
  user-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - e-commerce-dp
      - e-commerce-kafka
