
server:
  port: 8086 # Port for the Product Service
spring:

  kafka:

    bootstrap-servers: e-commerce-kafka:9092
    consumer:
      group-id: product-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      auto-create-topics: true # Automatically create topics if not already present


