spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_database
    username: ecommerce
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: e-commerce-kafka:9092